# -*- coding: utf-8 -*-
#    ufloat - fast python floats with physical units
#    Copyright (C) 2015  Christoph Gohle <christoph.gohle@mpq.mpg.de>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""
Created on Fri Nov 11 13:51:30 2016

@author: Christoph Gohle

if scipy is present use the physical constants defined in scipy.constants and 
make a version of them with ufloat units. We base our units system on 
(kg, m, s, G, V, C, A, K) and every unit is expressed in these terms (see funits).

We predefine some of the constants given in scipy.constants.physical_constants 
in this module (see default_names dictionary to find out how they are called).
if you need others you can use the function pc.

For example calling 
>>> pc('Newtonian constant of gravitation')
ufloat(6.67408e-11, {u'kg': -1.0, u's': -2.0, u'm': 3.0})
>>>


"""
from . import unit_from_string
from .ufloat import ufloat
from . import funits

try:
    from scipy import constants as scipyconstants
    have_scipy = True
except ImportError:
    have_scipy = False

default_names = {'Angstrom star': None,
 'Avogadro constant': 'N_A',
 'Bohr magneton': 'mu_b',
 'Bohr magneton in Hz/T': None,
 'Bohr magneton in K/T': None,
 'Bohr magneton in eV/T': None,
 'Bohr magneton in inverse meters per tesla': None,
 'Bohr radius': 'a_B',
 'Boltzmann constant': 'k',
 'Boltzmann constant in Hz/K': None,
 'Boltzmann constant in eV/K': None,
 'Boltzmann constant in inverse meters per kelvin': None,
 'Compton wavelength': 'lambda_c',
 'Compton wavelength over 2 pi': 'lambda_cbar',
 'Cu x unit': None,
 'Faraday constant': None,
 'Faraday constant for conventional electric current': None,
 'Fermi coupling constant': None,
 'Hartree energy': None,
 'Hartree energy in eV': None,
 'Josephson constant': None,
 'Loschmidt constant (273.15 K, 100 kPa)': None,
 'Loschmidt constant (273.15 K, 101.325 kPa)': None,
 'Mo x unit': None,
 'Newtonian constant of gravitation': None,
 'Newtonian constant of gravitation over h-bar c': None,
 'Planck constant': 'h',
 'Planck constant in eV s': None,
 'Planck constant over 2 pi': 'hbar',
 'Planck constant over 2 pi in eV s': None,
 'Planck constant over 2 pi times c in MeV fm': None,
 'Planck length': None,
 'Planck mass': 'm_P',
 'Planck mass energy equivalent in GeV': None,
 'Planck temperature': None,
 'Planck time': None,
 'Rydberg constant': 'Ry',
 'Rydberg constant times c in Hz': None,
 'Rydberg constant times hc in J': None,
 'Rydberg constant times hc in eV': None,
 'Sackur-Tetrode constant (1 K, 100 kPa)': None,
 'Sackur-Tetrode constant (1 K, 101.325 kPa)': None,
 'Stefan-Boltzmann constant': 'sigma',
 'Thomson cross section': None,
 'Wien displacement law constant': None,
 'Wien frequency displacement law constant': None,
 'Wien wavelength displacement law constant': None,
 'alpha particle mass': None,
 'alpha particle mass energy equivalent': None,
 'alpha particle mass energy equivalent in MeV': None,
 'alpha particle mass in u': None,
 'alpha particle molar mass': None,
 'alpha particle-electron mass ratio': None,
 'alpha particle-proton mass ratio': None,
 'atomic mass constant': 'u',
 'atomic mass constant energy equivalent': None,
 'atomic mass constant energy equivalent in MeV': None,
 'atomic mass unit-electron volt relationship': None,
 'atomic mass unit-hartree relationship': None,
 'atomic mass unit-hertz relationship': None,
 'atomic mass unit-inverse meter relationship': None,
 'atomic mass unit-joule relationship': None,
 'atomic mass unit-kelvin relationship': None,
 'atomic mass unit-kilogram relationship': None,
 'atomic unit of 1st hyperpolarizability': None,
 'atomic unit of 1st hyperpolarizablity': None,
 'atomic unit of 2nd hyperpolarizability': None,
 'atomic unit of 2nd hyperpolarizablity': None,
 'atomic unit of action': None,
 'atomic unit of charge': None,
 'atomic unit of charge density': None,
 'atomic unit of current': None,
 'atomic unit of electric dipole mom.': None,
 'atomic unit of electric dipole moment': None,
 'atomic unit of electric field': None,
 'atomic unit of electric field gradient': None,
 'atomic unit of electric polarizability': None,
 'atomic unit of electric polarizablity': None,
 'atomic unit of electric potential': None,
 'atomic unit of electric quadrupole mom.': None,
 'atomic unit of electric quadrupole moment': None,
 'atomic unit of energy': None,
 'atomic unit of force': None,
 'atomic unit of length': None,
 'atomic unit of mag. dipole mom.': None,
 'atomic unit of mag. flux density': None,
 'atomic unit of magn. dipole moment': None,
 'atomic unit of magn. flux density': None,
 'atomic unit of magnetizability': None,
 'atomic unit of mass': None,
 'atomic unit of mom.um': None,
 'atomic unit of momentum': None,
 'atomic unit of permittivity': None,
 'atomic unit of time': None,
 'atomic unit of velocity': None,
 'characteristic impedance of vacuum': None,
 'classical electron radius': None,
 'conductance quantum': None,
 'conventional value of Josephson constant': None,
 'conventional value of von Klitzing constant': None,
 'deuteron g factor': None,
 'deuteron mag. mom.': None,
 'deuteron mag. mom. to Bohr magneton ratio': None,
 'deuteron mag. mom. to nuclear magneton ratio': None,
 'deuteron magn. moment': None,
 'deuteron magn. moment to Bohr magneton ratio': None,
 'deuteron magn. moment to nuclear magneton ratio': None,
 'deuteron mass': None,
 'deuteron mass energy equivalent': None,
 'deuteron mass energy equivalent in MeV': None,
 'deuteron mass in u': None,
 'deuteron molar mass': None,
 'deuteron rms charge radius': None,
 'deuteron-electron mag. mom. ratio': None,
 'deuteron-electron magn. moment ratio': None,
 'deuteron-electron mass ratio': None,
 'deuteron-neutron mag. mom. ratio': None,
 'deuteron-neutron magn. moment ratio': None,
 'deuteron-proton mag. mom. ratio': None,
 'deuteron-proton magn. moment ratio': None,
 'deuteron-proton mass ratio': None,
 'electric constant': None,
 'electron charge to mass quotient': None,
 'electron g factor': 'ge',
 'electron gyromag. ratio': None,
 'electron gyromag. ratio over 2 pi': None,
 'electron gyromagn. ratio': None,
 'electron gyromagn. ratio over 2 pi': None,
 'electron mag. mom.': None,
 'electron mag. mom. anomaly': None,
 'electron mag. mom. to Bohr magneton ratio': None,
 'electron mag. mom. to nuclear magneton ratio': None,
 'electron magn. moment': None,
 'electron magn. moment anomaly': None,
 'electron magn. moment to Bohr magneton ratio': None,
 'electron magn. moment to nuclear magneton ratio': None,
 'electron mass': 'm_e',
 'electron mass energy equivalent': None,
 'electron mass energy equivalent in MeV': None,
 'electron mass in u': None,
 'electron molar mass': None,
 'electron to alpha particle mass ratio': None,
 'electron to shielded helion mag. mom. ratio': None,
 'electron to shielded helion magn. moment ratio': None,
 'electron to shielded proton mag. mom. ratio': None,
 'electron to shielded proton magn. moment ratio': None,
 'electron volt': None,
 'electron volt-atomic mass unit relationship': None,
 'electron volt-hartree relationship': None,
 'electron volt-hertz relationship': None,
 'electron volt-inverse meter relationship': None,
 'electron volt-joule relationship': None,
 'electron volt-kelvin relationship': None,
 'electron volt-kilogram relationship': None,
 'electron-deuteron mag. mom. ratio': None,
 'electron-deuteron magn. moment ratio': None,
 'electron-deuteron mass ratio': None,
 'electron-helion mass ratio': None,
 'electron-muon mag. mom. ratio': None,
 'electron-muon magn. moment ratio': None,
 'electron-muon mass ratio': None,
 'electron-neutron mag. mom. ratio': None,
 'electron-neutron magn. moment ratio': None,
 'electron-neutron mass ratio': None,
 'electron-proton mag. mom. ratio': None,
 'electron-proton magn. moment ratio': None,
 'electron-proton mass ratio': None,
 'electron-tau mass ratio': None,
 'electron-triton mass ratio': None,
 'elementary charge': 'e',
 'elementary charge over h': None,
 'fine-structure constant': 'alpha',
 'first radiation constant': None,
 'first radiation constant for spectral radiance': None,
 'hartree-atomic mass unit relationship': None,
 'hartree-electron volt relationship': None,
 'hartree-hertz relationship': None,
 'hartree-inverse meter relationship': None,
 'hartree-joule relationship': None,
 'hartree-kelvin relationship': None,
 'hartree-kilogram relationship': None,
 'helion g factor': None,
 'helion mag. mom.': None,
 'helion mag. mom. to Bohr magneton ratio': None,
 'helion mag. mom. to nuclear magneton ratio': None,
 'helion mass': None,
 'helion mass energy equivalent': None,
 'helion mass energy equivalent in MeV': None,
 'helion mass in u': None,
 'helion molar mass': None,
 'helion-electron mass ratio': None,
 'helion-proton mass ratio': None,
 'hertz-atomic mass unit relationship': None,
 'hertz-electron volt relationship': None,
 'hertz-hartree relationship': None,
 'hertz-inverse meter relationship': None,
 'hertz-joule relationship': None,
 'hertz-kelvin relationship': None,
 'hertz-kilogram relationship': None,
 'inverse fine-structure constant': None,
 'inverse meter-atomic mass unit relationship': None,
 'inverse meter-electron volt relationship': None,
 'inverse meter-hartree relationship': None,
 'inverse meter-hertz relationship': None,
 'inverse meter-joule relationship': None,
 'inverse meter-kelvin relationship': None,
 'inverse meter-kilogram relationship': None,
 'inverse of conductance quantum': None,
 'joule-atomic mass unit relationship': None,
 'joule-electron volt relationship': None,
 'joule-hartree relationship': None,
 'joule-hertz relationship': None,
 'joule-inverse meter relationship': None,
 'joule-kelvin relationship': None,
 'joule-kilogram relationship': None,
 'kelvin-atomic mass unit relationship': None,
 'kelvin-electron volt relationship': None,
 'kelvin-hartree relationship': None,
 'kelvin-hertz relationship': None,
 'kelvin-inverse meter relationship': None,
 'kelvin-joule relationship': None,
 'kelvin-kilogram relationship': None,
 'kilogram-atomic mass unit relationship': None,
 'kilogram-electron volt relationship': None,
 'kilogram-hartree relationship': None,
 'kilogram-hertz relationship': None,
 'kilogram-inverse meter relationship': None,
 'kilogram-joule relationship': None,
 'kilogram-kelvin relationship': None,
 'lattice parameter of silicon': None,
 'lattice spacing of silicon': None,
 'mag. constant': None,
 'mag. flux quantum': None,
 'magn. constant': None,
 'magn. flux quantum': None,
 'molar Planck constant': None,
 'molar Planck constant times c': None,
 'molar gas constant': None,
 'molar mass constant': None,
 'molar mass of carbon-12': None,
 'molar volume of ideal gas (273.15 K, 100 kPa)': None,
 'molar volume of ideal gas (273.15 K, 101.325 kPa)': None,
 'molar volume of silicon': None,
 'muon Compton wavelength': None,
 'muon Compton wavelength over 2 pi': None,
 'muon g factor': None,
 'muon mag. mom.': None,
 'muon mag. mom. anomaly': None,
 'muon mag. mom. to Bohr magneton ratio': None,
 'muon mag. mom. to nuclear magneton ratio': None,
 'muon magn. moment': None,
 'muon magn. moment to Bohr magneton ratio': None,
 'muon magn. moment to nuclear magneton ratio': None,
 'muon mass': None,
 'muon mass energy equivalent': None,
 'muon mass energy equivalent in MeV': None,
 'muon mass in u': None,
 'muon molar mass': None,
 'muon-electron mass ratio': None,
 'muon-neutron mass ratio': None,
 'muon-proton mag. mom. ratio': None,
 'muon-proton magn. moment ratio': None,
 'muon-proton mass ratio': None,
 'muon-tau mass ratio': None,
 'natural unit of action': None,
 'natural unit of action in eV s': None,
 'natural unit of energy': None,
 'natural unit of energy in MeV': None,
 'natural unit of length': None,
 'natural unit of mass': None,
 'natural unit of mom.um': None,
 'natural unit of mom.um in MeV/c': None,
 'natural unit of momentum': None,
 'natural unit of momentum in MeV/c': None,
 'natural unit of time': None,
 'natural unit of velocity': None,
 'neutron Compton wavelength': None,
 'neutron Compton wavelength over 2 pi': None,
 'neutron g factor': None,
 'neutron gyromag. ratio': None,
 'neutron gyromag. ratio over 2 pi': None,
 'neutron gyromagn. ratio': None,
 'neutron gyromagn. ratio over 2 pi': None,
 'neutron mag. mom.': None,
 'neutron mag. mom. to Bohr magneton ratio': None,
 'neutron mag. mom. to nuclear magneton ratio': None,
 'neutron magn. moment': None,
 'neutron magn. moment to Bohr magneton ratio': None,
 'neutron magn. moment to nuclear magneton ratio': None,
 'neutron mass': None,
 'neutron mass energy equivalent': None,
 'neutron mass energy equivalent in MeV': None,
 'neutron mass in u': None,
 'neutron molar mass': None,
 'neutron to shielded proton mag. mom. ratio': None,
 'neutron to shielded proton magn. moment ratio': None,
 'neutron-electron mag. mom. ratio': None,
 'neutron-electron magn. moment ratio': None,
 'neutron-electron mass ratio': None,
 'neutron-muon mass ratio': None,
 'neutron-proton mag. mom. ratio': None,
 'neutron-proton magn. moment ratio': None,
 'neutron-proton mass difference': None,
 'neutron-proton mass difference energy equivalent': None,
 'neutron-proton mass difference energy equivalent in MeV': None,
 'neutron-proton mass difference in u': None,
 'neutron-proton mass ratio': None,
 'neutron-tau mass ratio': None,
 'nuclear magneton': None,
 'nuclear magneton in K/T': None,
 'nuclear magneton in MHz/T': None,
 'nuclear magneton in eV/T': None,
 'nuclear magneton in inverse meters per tesla': None,
 'proton Compton wavelength': None,
 'proton Compton wavelength over 2 pi': None,
 'proton charge to mass quotient': None,
 'proton g factor': 'g_P',
 'proton gyromag. ratio': None,
 'proton gyromag. ratio over 2 pi': None,
 'proton gyromagn. ratio': None,
 'proton gyromagn. ratio over 2 pi': None,
 'proton mag. mom.': None,
 'proton mag. mom. to Bohr magneton ratio': None,
 'proton mag. mom. to nuclear magneton ratio': None,
 'proton mag. shielding correction': None,
 'proton magn. moment': None,
 'proton magn. moment to Bohr magneton ratio': None,
 'proton magn. moment to nuclear magneton ratio': None,
 'proton magn. shielding correction': None,
 'proton mass': None,
 'proton mass energy equivalent': None,
 'proton mass energy equivalent in MeV': None,
 'proton mass in u': None,
 'proton molar mass': None,
 'proton rms charge radius': None,
 'proton-electron mass ratio': None,
 'proton-muon mass ratio': None,
 'proton-neutron mag. mom. ratio': None,
 'proton-neutron magn. moment ratio': None,
 'proton-neutron mass ratio': None,
 'proton-tau mass ratio': None,
 'quantum of circulation': None,
 'quantum of circulation times 2': None,
 'second radiation constant': None,
 'shielded helion gyromag. ratio': None,
 'shielded helion gyromag. ratio over 2 pi': None,
 'shielded helion gyromagn. ratio': None,
 'shielded helion gyromagn. ratio over 2 pi': None,
 'shielded helion mag. mom.': None,
 'shielded helion mag. mom. to Bohr magneton ratio': None,
 'shielded helion mag. mom. to nuclear magneton ratio': None,
 'shielded helion magn. moment': None,
 'shielded helion magn. moment to Bohr magneton ratio': None,
 'shielded helion magn. moment to nuclear magneton ratio': None,
 'shielded helion to proton mag. mom. ratio': None,
 'shielded helion to proton magn. moment ratio': None,
 'shielded helion to shielded proton mag. mom. ratio': None,
 'shielded helion to shielded proton magn. moment ratio': None,
 'shielded proton gyromag. ratio': None,
 'shielded proton gyromag. ratio over 2 pi': None,
 'shielded proton mag. mom.': None,
 'shielded proton mag. mom. to Bohr magneton ratio': None,
 'shielded proton mag. mom. to nuclear magneton ratio': None,
 'shielded proton magn. moment': None,
 'shielded proton magn. moment to Bohr magneton ratio': None,
 'shielded proton magn. moment to nuclear magneton ratio': None,
 'speed of light in vacuum': 'c',
 'standard acceleration of gravity': 'g',
 'standard atmosphere': None,
 'standard-state pressure': None,
 'tau Compton wavelength': None,
 'tau Compton wavelength over 2 pi': None,
 'tau mass': None,
 'tau mass energy equivalent': None,
 'tau mass energy equivalent in MeV': None,
 'tau mass in u': None,
 'tau molar mass': None,
 'tau-electron mass ratio': None,
 'tau-muon mass ratio': None,
 'tau-neutron mass ratio': None,
 'tau-proton mass ratio': None,
 'triton g factor': None,
 'triton mag. mom.': None,
 'triton mag. mom. to Bohr magneton ratio': None,
 'triton mag. mom. to nuclear magneton ratio': None,
 'triton mass': None,
 'triton mass energy equivalent': None,
 'triton mass energy equivalent in MeV': None,
 'triton mass in u': None,
 'triton molar mass': None,
 'triton-electron mag. mom. ratio': None,
 'triton-electron mass ratio': None,
 'triton-neutron mag. mom. ratio': None,
 'triton-proton mag. mom. ratio': None,
 'triton-proton mass ratio': None,
 'unified atomic mass unit': None,
 'von Klitzing constant': None,
 'weak mixing angle': None,
 '{220} lattice spacing of silicon': None}
    
def pc(name):
    v, u, p = scipyconstants.physical_constants[name]
    ufix = u.replace('^','**')
    u = unit_from_string(ufix)
    #normalize units
    unorm = 1
    remain = {}
    for s,e in u.items():
        if hasattr(funits, s):
            unorm*=getattr(funits,s)**e
        else:
            remain[s]=e
    if len(remain)>0:
        unorm = unorm*ufloat(1,remain)
        
    return v*unorm
        
if have_scipy:
    for n, s in default_names.items():
        if s is not None:
            globals()[s] = pc(n)
    import scipy
    mu_0 = 4e-7*scipy.pi
    epsilon_0 = 1 / (mu_0*c*c) #analysis:ignore